spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/film-catalog
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: film-catalog


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration