spring:
  config:
    activate:
      on-profile: circuitbreaker
resilience4j.circuitbreaker:
  metrics:
    enabled: true
  configs:
    default:
      registerHealthIndicator: true
      allowHealthIndicatorToFail: true
      minimumNumberOfCalls: 10
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 3
      failureRateThreshold: 60
      slowCallDurationThreshold: 3000
      slowCallRateThreshold: 90
      permittedNumberOfCallsInHalfOpenState: 5
      waitDurationInOpenState: 3000
  instances:
    bookServiceCircuitBreaker:
      baseConfig: default
      ignoreExceptions:
        - ru.otus.library.exceptions.BookNotFoundException
    authorServiceCircuitBreaker:
      base-config: default
    categoryServiceCircuitBreaker:
      base-config: default
    commentServiceCircuitBreaker:
      base-config: default