spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:/db/migration