spring:
  data:
    mongodb:
      database: library
      host: localhost
      port: 27017


mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.library.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local